POST http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1c2giLCJpZCI6IjY4YjZkNzk5NzQzNzNjZmExYmYwODU0OCIsImlhdCI6MTc1Njk1NTA4NSwiZXhwIjoxNzU2OTU4Njg1fQ.AQCLhWNT5Vzm_3Y14dAYhjuH0sTQOhS85_t49Z48MyM
Content-Type: application/json

{
    "title": "Fourty Thousand Weeks",
    "author": "Oliver Burkeman",
    "url": "https://www.oliverburkeman.com/fourthousandweeks",
    "likes": 0
}