DELETE http://localhost:3003/api/blogs/68ad856eb387165d1f7d757d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjhhZDI1OGRmM2M1MzZmZjMxZDdjYWUwIiwiaWF0IjoxNzU2MTk5Mzc5LCJleHAiOjE3NTYyMDI5Nzl9.3xY9Xlk1DXD_7WC-b3GeVCs42JR3tYWLbSIDaZnj-WQ
Content-Type: application/json